/* Builds index.html and files/*.html from src/ plus spec.json and the two
   implementations. Everything the pages show is resolved here, at build time:
   the published site fetches nothing and needs no JavaScript to render.

   Run: node tools/build-site.mjs
   Verify: node tools/check.mjs
*/

import { readFileSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import { renderPanel } from '../src/panels.mjs';
import { byLang, esc } from '../src/highlight.mjs';

/* The whole file is highlighted in one pass — a multi-line CSS comment needs
   state that carries between lines — and only then split for numbering. */
function lineNumbered(source, lang) {
  const text = source.replace(/\n$/, '');
  const html = byLang(lang, text).split('\n');
  return text.split('\n').map((_, i) =>
    `<div class="line" id="L${i + 1}"><span class="no">${i + 1}</span>`
    + `<span class="src">${html[i] ?? ''}</span></div>`).join('');
}

const read = (p) => readFileSync(p, 'utf8');

/* Returns every generated file as path -> contents. Nothing is written here, so
   tools/check.mjs can rebuild in memory and compare against what is committed —
   which makes a stale generated page a build failure rather than a surprise. */
export function buildAll() {
const spec = JSON.parse(read('spec.json'));
const sections = JSON.parse(read('src/sections.json'));
const output = new Map();

/* ---- Marker extraction, the same contract the sources declare ------------- */

function markers(source, re, group) {
  const found = new Map();
  let m;
  while ((m = re.exec(source)) !== null) {
    found.set(m[1], m[group].replace(/\n{3,}/g, '\n\n').trim());
  }
  return found;
}

const cssMap = markers(read('typeset.css'),
  /\/\*!\s*@s\s+([a-z0-9-]+)\s*::\s*(.+?)\s*\*\/([\s\S]*?)\/\*!\s*@e\s*\*\//g, 3);
const typMap = markers(read('implementations/typeset.typ'),
  /\/\/\s*@s\s+([a-z0-9-]+)\s*\n([\s\S]*?)\/\/\s*@e/g, 2);

/* ---- Page shell ---------------------------------------------------------- */

const FONTS = 'https://fonts.googleapis.com/css2'
  + '?family=EB+Garamond:ital,wght@0,400..800;1,400..800'
  + '&family=Source+Sans+3:ital,wght@0,300..700;1,300..700'
  + '&family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&display=swap';

function shell({ title, description, head = '', body, scripts = '' }) {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title}</title>
<meta name="description" content="${esc(description)}">
<!-- Generated by tools/build-site.mjs from src/. Do not edit by hand. -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="${FONTS}">
${head}</head>
<body>
${body}
${scripts}</body>
</html>
`;
}

/* ---- index.html --------------------------------------------------------- */

function nav() {
  const groups = [...new Set(sections.map((s) => s.group))];
  const blocks = groups.map((g) => {
    /* The nav uses a shorter label than the section title where one is given:
       a sidebar entry has less room than a heading. */
    const items = sections.filter((s) => s.group === g)
      .map((s) => `    <li><a href="#${s.id}">${s.nav || s.title}</a></li>`).join('\n');
    return `  <p class="nav__group">${g}</p>\n  <ol>\n${items}\n  </ol>`;
  });
  return [read('src/nav-top.html').trimEnd(), ...blocks, read('src/nav-bottom.html').trimEnd()]
    .join('\n\n');
}

function section(s, index) {
  const num = String(index + 1).padStart(2, '0');
  const prose = s.prose.map((p) => `    ${p}`).join('\n');
  const note = s.note ? `  ${s.note}\n` : '';
  const demo = read(`src/demos/${s.id}.html`).trimEnd()
    .split('\n').map((l) => (l ? `      ${l}` : l)).join('\n');
  const fullrow = s.fullrow
    ? '\n' + read(`src/demos/${s.id}.fullrow.html`).trimEnd()
        .split('\n').map((l) => (l ? `  ${l}` : l)).join('\n') + '\n'
    : '';
  const panel = renderPanel({
    spec, cssMap, typMap, id: s.id,
    specIds: s.panel.spec,
    cssKeys: (s.panel.css || s.panel.spec).split(',').map((k) => k.trim()),
  }).split('\n').map((l) => (l ? `      ${l}` : l)).join('\n');

  return `<section class="section" id="${s.id}">
  <div class="section__head">
    <p class="section__num">${num} — ${s.group}</p>
    <h2>${s.title}</h2>
${prose}
  </div>
${note}  <div class="pair">
    <div>
${demo}
    </div>
    <div>
${panel}
    </div>
  </div>
${fullrow}</section>`;
}

const counts = (() => {
  const els = spec.sections.reduce((n, s) => n + s.elements.length, 0);
  const templates = Object.keys(spec.templates)
    .filter((k) => k !== 'default' && k !== 'note').length;
  return `${spec.sections.length} sections, ${els} elements, ${templates} templates`;
})();

const masthead = read('src/masthead.html').trimEnd()
  .replace('<span data-spec-counts>every value</span>', counts)
  .replace('<span data-spec-version>—</span>', `${spec.version} · ${spec.updated}`);

output.set('index.html', shell({
  title: 'typeset — a typographic specification',
  description: "Adilson Carvalho's typographic specification for printed documents: "
    + 'essays, letters, reports. Rendered examples beside the values every engine must hit.',
  head: `<link rel="stylesheet" href="typeset.css">\n<link rel="stylesheet" href="specimen.css">\n`,
  body: `<div class="shell">

<nav class="nav">
  <p class="nav__brand"><a href="#top">typeset</a></p>
  <p class="nav__tagline">A typographic standard for printed documents.</p>

${nav()}
</nav>

<main class="main" id="top">

${masthead}

${sections.map(section).join('\n\n')}

${read('src/footer.html').trimEnd()}

</main>
</div>`,
  scripts: '<script src="specimen.js" defer></script>\n',
}));

/* ---- files/*.html — one viewer per downloadable ------------------------- */

const VIEWERS = JSON.parse(read('src/viewers.json'));

for (const v of VIEWERS) {
  const source = read(v.source);
  const lines = source.replace(/\n$/, '').split('\n').length;
  const kb = (Buffer.byteLength(source, 'utf8') / 1024).toFixed(1);

  output.set(`files/${v.slug}.html`, shell({
    title: `${v.name} — typeset`,
    description: v.description,
    head: `<link rel="stylesheet" href="../specimen.css">\n<link rel="stylesheet" href="viewer.css">\n`,
    body: `<div class="vbar">
  <a class="back" href="../index.html">← typeset</a>
  <span class="name">${v.name}</span>
  <span class="actions">
    <button class="vbtn" type="button" data-copy>Copy</button>
    <a class="vbtn" href="${v.href}" download>Download</a>
  </span>
</div>

<main>
  <h1>${v.name}</h1>
  <p class="lede">${v.lede}</p>
${v.extra ? `  <div class="extra">\n    ${v.extra}\n  </div>\n` : ''}  <p class="meta">${lines} lines · ${kb} KB</p>
  <div class="filebody">${lineNumbered(source, v.lang)}</div>
</main>`,
    scripts: '<script src="viewer.js" defer></script>\n',
  }));
}

  return { output, stats: {
    sections: sections.length,
    navLinks: nav().match(/<li>/g).length,
    viewers: VIEWERS.length,
    cssMarkers: cssMap.size,
    typstMarkers: typMap.size,
  } };
}

/* CLI */
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { output, stats } = buildAll();
  for (const [path, contents] of output) writeFileSync(path, contents);
  console.log(`index.html — ${stats.sections} sections, ${stats.navLinks} nav links`);
  console.log(`files/ — ${stats.viewers} viewer pages`);
  console.log(`markers resolved — css ${stats.cssMarkers}, typst ${stats.typstMarkers}`);
}
