/* Builds index.html and files/*.html from src/ plus spec.json and the two
   implementations. Everything the pages show is resolved here, at build time:
   the published site fetches nothing to render its content. The Typst example
   viewer pages are the one place that still reaches for JavaScript at load
   time — to swap in a message when previews/ has not been built, since this
   script has no compiler on PATH and so cannot tell at build time whether it
   has (see tools/build-previews.mjs).

   Run: node tools/build-site.mjs
   Verify: node tools/check.mjs
*/

import { readFileSync, writeFileSync } from 'node:fs';
import { basename } from 'node:path';
import { pathToFileURL } from 'node:url';
import { renderPanel } from '../src/panels.mjs';
import { byLang, esc } from '../src/highlight.mjs';
import { EXAMPLES } from '../src/examples.mjs';
import { extractDemos, verbatimLineMask } from '../src/extract.mjs';
import { typstBoilerplate } from '../src/boilerplate.mjs';

/* The whole file is highlighted in one pass — a multi-line CSS comment needs
   state that carries between lines — and only then split for numbering. */
function lineNumbered(source, lang) {
  const text = source.replace(/\n$/, '');
  const html = byLang(lang, text).split('\n');
  return text.split('\n').map((_, i) =>
    `<div class="line" id="L${i + 1}"><span class="no">${i + 1}</span>`
    + `<span class="src">${html[i] ?? ''}</span></div>`).join('');
}

const read = (p) => readFileSync(p, 'utf8');

/* Returns every generated file as path -> contents. Nothing is written here, so
   tools/check.mjs can rebuild in memory and compare against what is committed —
   which makes a stale generated page a build failure rather than a surprise. */
export function buildAll() {
const spec = JSON.parse(read('spec.json'));
const sections = JSON.parse(read('src/sections.json'));
const output = new Map();

/* ---- Marker extraction, the same contract the sources declare ------------- */

function markers(source, re, group) {
  const found = new Map();
  let m;
  while ((m = re.exec(source)) !== null) {
    found.set(m[1], m[group].replace(/\n{3,}/g, '\n\n').trim());
  }
  return found;
}

/* Full CSS source per "@s" region, for the sections whose panel.pane in
   sections.json is "css" rather than "html" — they state values rather
   than demonstrate a document, so there is no markup for a reader to copy
   and the values themselves are the thing on show. */
const cssMap = markers(read('typeset.css'),
  /\/\*!\s*@s\s+([a-z0-9-]+)\s*::[^\n]*\*\/\n([\s\S]*?)\/\*!\s*@e\s*\*\//g, 2);

/* The 1-based source line each "@s" marker starts at, for linking a section's
   HTML pane back to its region in files/typeset-css.html — which anchors
   every line with id="L<n>" (see lineNumbered() below). Read from the file
   itself rather than a hand-maintained table, so a line added above any
   marker cannot leave a stale link behind. */
function markerLines(source, re) {
  const found = new Map();
  let m;
  while ((m = re.exec(source)) !== null) {
    found.set(m[1], source.slice(0, m.index).split('\n').length);
  }
  return found;
}

const cssLines = markerLines(read('typeset.css'), /\/\*!\s*@s\s+([a-z0-9-]+)\s*::/g);

/* The same, for typeset.typ's "@s" markers, so a section's Typst pane can
   link into files/typeset-typ.html the way its HTML pane links into
   files/typeset-css.html. Not every section marks a region of its own —
   src/panels.mjs falls back from there. */
const typLines = markerLines(read('implementations/typeset.typ'), /\/\/\s*@s\s+([a-z0-9-]+)\s*\n/g);

/* ---- Page shell ---------------------------------------------------------- */

const FONTS = 'https://fonts.googleapis.com/css2'
  + '?family=EB+Garamond:ital,wght@0,400..800;1,400..800'
  + '&family=Source+Sans+3:ital,wght@0,300..700;1,300..700'
  + '&family=IBM+Plex+Mono:ital,wght@0,400;0,600;1,400&display=swap';

function shell({ title, description, head = '', body, scripts = '' }) {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title}</title>
<meta name="description" content="${esc(description)}">
<!-- Generated by tools/build-site.mjs from src/. Do not edit by hand. -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="${FONTS}">
${head}</head>
<body>
${body}
${scripts}</body>
</html>
`;
}

/* ---- index.html --------------------------------------------------------- */

function nav() {
  const groups = [...new Set(sections.map((s) => s.group))];
  const blocks = groups.map((g) => {
    /* The nav uses a shorter label than the section title where one is given:
       a sidebar entry has less room than a heading. */
    const items = sections.filter((s) => s.group === g)
      .map((s) => `    <li><a href="#${s.id}">${s.nav || s.title}</a></li>`).join('\n');
    return `  <p class="nav__group">${g}</p>\n  <ol>\n${items}\n  </ol>`;
  });
  return [read('src/nav-top.html').trimEnd(), ...blocks, read('src/nav-bottom.html').trimEnd()]
    .join('\n\n');
}

/* Sets a demo file at the depth the page nests it to, without touching a line
   whose leading whitespace is content rather than markup indentation. A <pre>
   is the case that matters: src/demos/codeblock.html holds a CSS sample whose
   own lines are indented two spaces, and prefixing those lines publishes the
   section about setting code with its own example misindented. Which lines
   those are is decided by src/extract.mjs's mask, so the demo column and the
   pane beside it agree about where whitespace is content. */
function indentMarkup(source, pad) {
  const text = source.trimEnd();
  const verbatim = verbatimLineMask(text);
  return text.split('\n')
    .map((line, i) => (line && !verbatim[i] ? pad + line : line))
    .join('\n');
}

function section(s, index) {
  const num = String(index + 1).padStart(2, '0');
  const prose = s.prose.map((p) => `    ${p}`).join('\n');
  const note = s.note ? `  ${s.note}\n` : '';
  const demoSource = read(`src/demos/${s.id}.html`);
  const demo = indentMarkup(demoSource, '      ');
  const fullrow = s.fullrow
    ? `\n${indentMarkup(read(`src/demos/${s.id}.fullrow.html`), '  ')}\n`
    : '';
  /* Left at its own indent, not re-indented line by line like demo/fullrow
     below: the panel's HTML and Typst panes hold <pre> content a reader
     copies, where whitespace is part of what gets copied, and prefixing
     every line would corrupt it. */
  const panel = renderPanel({
    spec, cssLines, cssMap, typLines, id: s.id,
    specIds: s.panel.spec,
    pane: s.panel.pane,
    cssKeys: (s.panel.css || s.panel.spec).split(',').map((k) => k.trim()),
    fragments: extractDemos(demoSource),
    typSource: read(`src/demos/${s.id}.typ`).trimEnd(),
  });

  return `<section class="section" id="${s.id}">
  <div class="section__head">
    <p class="section__num">${num} — ${s.group}</p>
    <h2>${s.title}</h2>
${prose}
  </div>
${note}  <div class="pair">
    <div>
${demo}
    </div>
    <div>
${panel}
    </div>
  </div>
${fullrow}</section>`;
}

/* ---- Masthead boilerplate -------------------------------------------------
   The block every reader needs once, above the sections: what to add around
   a copied HTML or Typst snippet to make it run. Both halves are read from
   the files that already own the values they state, so the block can never
   drift from the fonts fonts/ actually carries or the import shape
   typeset.typ actually declares. */

/* The weight a face's filename names, where it names it in words. A file whose
   suffix is numeric carries the weight directly. */
const WEIGHT_NAMES = {
  '': 400, Thin: 100, ExtraLight: 200, Light: 300, Regular: 400,
  Medium: 500, SemiBold: 600, Bold: 700, ExtraBold: 800, Black: 900,
};

/* The font-weight and font-style descriptors a face file must be bound with,
   read from the part of its name after the family: "-SemiBoldItalic", "-400",
   "-300", "-Italic". Returns null for a name this cannot read, which the
   caller turns into a build failure — a face bound with the wrong descriptors,
   or with none, is exactly the defect this block exists to prevent. */
function faceDescriptors(file) {
  const stem = file.replace(/\.(otf|ttf|woff2?)$/i, '');
  const suffix = stem.slice(stem.indexOf('-') + 1);
  const italic = suffix.endsWith('Italic');
  const token = italic ? suffix.slice(0, -'Italic'.length) : suffix;
  const weight = /^\d+$/.test(token) ? Number(token) : WEIGHT_NAMES[token];
  if (weight === undefined) return null;
  return { weight, style: italic ? 'italic' : 'normal' };
}

/* Every face the three spec families carry, each bound with the descriptors
   its own filename declares. A @font-face rule with no font-weight and no
   font-style tells the browser the file is the family's 400 upright, so it
   answers a request for 600 or for italic by slanting and smearing that one
   file — and typeset.css asks for sans 300/600/700 and for serif italic and
   semibold. Faux bold and faux italic on the front page of a typographic
   specification is the failure the specification exists to prevent, so the
   list is derived from fonts/manifest.json rather than hand-kept: a face that
   is added, renamed or removed moves this block with it. */
function boilerplateHtml() {
  const manifest = JSON.parse(read('fonts/manifest.json'));
  const blocks = ['serif', 'sans', 'mono'].map((role) => {
    const { family } = spec.foundation.fonts[role];
    const entry = manifest.families.find((f) => f.family === family && f.role === 'spec');
    if (!entry) {
      throw new Error(`fonts/manifest.json has no "spec" entry for ${family}, which `
        + `spec.foundation.fonts.${role} names — regenerate the manifest`);
    }
    return entry.faces.map((face) => {
      const d = faceDescriptors(face.file);
      if (!d) {
        throw new Error(`fonts/manifest.json: cannot read a weight and style out of `
          + `"${face.file}" — teach faceDescriptors() in tools/build-site.mjs its shape, `
          + 'or the masthead would bind it with no descriptors and the browser would '
          + 'synthesise every other weight from it');
      }
      return { ...d, src: `${entry.dir}/${face.file}`, family };
    })
      .sort((a, b) => (a.style === b.style ? a.weight - b.weight : (a.style === 'normal' ? -1 : 1)))
      .map((f) => `  @font-face { font-family: "${f.family}"; font-weight: ${f.weight};`
        + ` font-style: ${f.style}; src: url("${f.src}"); }`)
      .join('\n');
  });
  return esc(`<link rel="stylesheet" href="typeset.css">
<style>
${blocks.join('\n\n')}
</style>

<div class="typeset">
  <!-- the fragment from any HTML pane goes here -->
</div>`);
}

/* The same text tools/check.mjs compiles every snippet under, from the same
   function — so the block a reader is told to paste above a snippet and the
   block the gate proves a snippet runs under cannot be two different things. */
function boilerplateTypst() {
  return byLang('typst', typstBoilerplate());
}

/* One button per shipped Typst example, in src/examples.mjs's own order —
   the same source the viewer pages below come from, so an example added,
   renamed or reordered there moves here with it rather than needing a
   second, hand-kept button list. */
function typstExampleButtons() {
  return EXAMPLES.map((e) => {
    const label = e.id.replace(/-/g, ' ').replace(/^./, (c) => c.toUpperCase());
    return `<a class="btn" href="files/example-${e.id}.html">${label}</a>`;
  }).join('\n        ');
}

const masthead = read('src/masthead.html').trimEnd()
  .replace('<span data-spec-version>—</span>', `${spec.version} · ${spec.updated}`)
  .replace('<span data-typst-examples></span>', typstExampleButtons())
  .replace('<code data-boilerplate="html"></code>', `<code data-boilerplate="html">${boilerplateHtml()}</code>`)
  .replace('<code data-boilerplate="typst"></code>', `<code data-boilerplate="typst">${boilerplateTypst()}</code>`);

output.set('index.html', shell({
  title: 'typeset — a typographic specification',
  description: "Adilson Carvalho's typographic specification for printed documents: "
    + 'essays, letters, reports. Rendered examples beside the values every engine must hit.',
  head: `<link rel="stylesheet" href="typeset.css">\n<link rel="stylesheet" href="specimen.css">\n`,
  body: `<div class="shell">

<nav class="nav">
  <p class="nav__brand"><a href="#top">typeset</a></p>
  <p class="nav__tagline">A typographic standard for printed documents.</p>

${nav()}
</nav>

<main class="main" id="top">

${masthead}

${sections.map(section).join('\n\n')}

${read('src/footer.html').trimEnd()}

</main>
</div>`,
  scripts: '<script src="specimen.js" defer></script>\n',
}));

/* ---- files/*.html — one viewer per downloadable, plus one per shipped
   Typst example with its rendered preview above the source ---------------- */

/* The sticky bar, source pane and (when given) preview block every viewer
   page shares — src/viewers.json's five entries and src/examples.mjs's three
   examples are different kinds of row, but they render through the one
   function, so they cannot drift into two different page shapes. */
function viewerBody({ name, href, lede, extra, source, lang, preview = '' }) {
  const lines = source.replace(/\n$/, '').split('\n').length;
  const kb = (Buffer.byteLength(source, 'utf8') / 1024).toFixed(1);
  return `<div class="vbar">
  <a class="back" href="../index.html">← typeset</a>
  <span class="name">${name}</span>
  <span class="actions">
    <button class="vbtn" type="button" data-copy>Copy</button>
    <a class="vbtn" href="${href}" download>Download</a>
  </span>
</div>

<main>
  <h1>${name}</h1>
  <p class="lede">${lede}</p>
${preview}${extra ? `  <div class="extra">\n    ${extra}\n  </div>\n` : ''}  <p class="meta">${lines} lines · ${kb} KB</p>
  <div class="filebody">${lineNumbered(source, lang)}</div>
</main>`;
}

const VIEWERS = JSON.parse(read('src/viewers.json'));

for (const v of VIEWERS) {
  output.set(`files/${v.slug}.html`, shell({
    title: `${v.name} — typeset`,
    description: v.description,
    head: `<link rel="stylesheet" href="../specimen.css">\n<link rel="stylesheet" href="viewer.css">\n`,
    body: viewerBody({
      name: v.name, href: v.href, lede: v.lede, extra: v.extra,
      source: read(v.source), lang: v.lang,
    }),
    scripts: '<script src="viewer.js" defer></script>\n',
  }));
}

/* One page per shipped Typst example (src/examples.mjs) — derived rather than
   a fourth hand-typed copy of that list in src/viewers.json, which is exactly
   the duplication tools/build-bundle.mjs, tools/build-previews.mjs and
   tools/check.mjs were collapsed onto one source to remove.

   The rendered preview goes first, above the source: previews/<id>-<n>.svg is
   built separately, by tools/build-previews.mjs, because it needs Typst and
   this script must not. So every <img> ships unconditionally — regenerating
   this page never depends on whether previews/ happens to exist on the
   machine running it — and viewer.js swaps in the "not built" message only if
   the first page actually fails to load. */
for (const e of EXAMPLES) {
  const name = basename(e.file);
  const lede = `A conformance sample for the Typst implementation — ${e.description}. Rendered `
    + `below from <a href="typeset-typ.html">typeset.typ</a>; the checker compiles it fresh on `
    + 'every commit.';
  const pages = Array.from({ length: e.pages }, (_, i) => i + 1)
    .map((n) => `      <img src="../previews/${e.id}-${n}.svg" alt="${e.id}, page ${n}"`
      + `${n > 1 ? ' loading="lazy"' : ''}>`)
    .join('\n');
  const preview = `  <section class="preview" data-preview>
    <p class="preview__missing" hidden>Rendered pages are not built in this checkout. Run
      <code>node tools/build-previews.mjs</code> to generate them — Typst must be on
      <code>PATH</code>.</p>
    <div class="preview__pages">
${pages}
    </div>
  </section>
`;

  output.set(`files/example-${e.id}.html`, shell({
    title: `${name} — typeset`,
    description: `A Typst conformance sample: ${e.description}. One of the three example `
      + 'documents typeset.typ ships with.',
    head: `<link rel="stylesheet" href="../specimen.css">\n<link rel="stylesheet" href="viewer.css">\n`,
    body: viewerBody({ name, href: `../${e.file}`, lede, source: read(e.file), lang: 'typst', preview }),
    scripts: '<script src="viewer.js" defer></script>\n',
  }));
}

  return { output, stats: {
    sections: sections.length,
    navLinks: nav().match(/<li>/g).length,
    viewers: VIEWERS.length + EXAMPLES.length,
    cssMarkers: cssLines.size,
    typstMarkers: typLines.size,
  } };
}

/* CLI */
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { output, stats } = buildAll();
  for (const [path, contents] of output) writeFileSync(path, contents);
  console.log(`index.html — ${stats.sections} sections, ${stats.navLinks} nav links`);
  console.log(`files/ — ${stats.viewers} viewer pages`);
  console.log(`markers resolved — css ${stats.cssMarkers}, typst ${stats.typstMarkers}`);
}
