/* Generates SPEC.md from spec.json. spec.json is normative; SPEC.md is a
   rendering of it for people and for pasting into a model's context.

   One source, two consumers, the same shape tools/build-site.mjs uses:
   buildSpecMd() returns the text and writes nothing, so tools/check.mjs can
   regenerate it and compare byte for byte instead of sampling a version line.

   Run: node tools/build-spec.mjs */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';

export function buildSpecMd(spec) {
const out = [];
const w = (s = '') => out.push(s);

const label = (k) => k.replace(/_/g, ' ');
const fmt = (v) => {
  if (Array.isArray(v)) return v.map((x) => `\`${x}\``).join(', ');
  if (typeof v === 'boolean') return v ? 'yes' : 'no';
  if (v && typeof v === 'object') return Object.entries(v).map(([k, x]) => `${label(k)}: \`${x}\``).join('; ');
  if (typeof v === 'number') return `\`${v}\``;
  return /^[a-z0-9_.#%+-]+(\s(pt|mm|em))?$/i.test(v) || String(v).length < 26 ? `\`${v}\`` : String(v);
};

function table(obj) {
  w('| Property | Value |');
  w('| --- | --- |');
  for (const [k, v] of Object.entries(obj)) w(`| ${label(k)} | ${fmt(v)} |`);
  w();
}

w(`# ${spec.name} — typographic specification`);
w();
w(`Version ${spec.version} · updated ${spec.updated} · ${spec.owner}`);
w(`Canonical: ${spec.canonical_url}`);
w();
w(spec.intent);
w();
w(`**Target.** ${spec.target}`);
w();
w('## Conformance');
w();
for (const r of spec.conformance) w(`- ${r}`);
w();
w('## Foundation');
w();

for (const [group, data] of Object.entries(spec.foundation)) {
  w(`### ${label(group)}`);
  w();
  const flat = Object.fromEntries(
    Object.entries(data).filter(([, v]) => !v || typeof v !== 'object' || Array.isArray(v)),
  );
  if (Object.keys(flat).length) table(flat);
  for (const [k, v] of Object.entries(data)) {
    if (v && typeof v === 'object' && !Array.isArray(v)) {
      w(`#### ${label(k)}`);
      w();
      table(v);
    }
  }
}

w('## Templates');
w();
w(spec.templates.note);
w();
w(`Default: \`${spec.templates.default}\``);
w();

for (const [id, t] of Object.entries(spec.templates)) {
  if (id === 'default' || id === 'note') continue;
  w(`### ${t.name}`);
  w();
  w(`\`${id}\`${t.opt_in ? ` · opt-in: \`${t.opt_in}\`` : ''}`);
  w();
  w(`**Use for.** ${t.use_for}`);
  w();
  for (const [k, v] of Object.entries(t)) {
    if (['name', 'id', 'opt_in', 'use_for'].includes(k)) continue;
    if (Array.isArray(v)) {
      w(`#### ${label(k)}`); w();
      for (const item of v) w(`- ${item}`);
      w();
    } else if (v && typeof v === 'object') {
      w(`#### ${label(k)}`); w();
      const flat = Object.fromEntries(Object.entries(v).filter(([, x]) => !x || typeof x !== 'object' || Array.isArray(x)));
      if (Object.keys(flat).length) table(flat);
      for (const [k2, v2] of Object.entries(v)) {
        if (v2 && typeof v2 === 'object' && !Array.isArray(v2)) {
          w(`**${label(k2)}**`); w(); table(v2);
        }
      }
    } else {
      w(`**${label(k)}.** ${v}`); w();
    }
  }
}

w('## Elements');
w();

let group = null;
for (const sec of spec.sections) {
  if (sec.group !== group) {
    group = sec.group;
    w(`### ${group}`);
    w();
  }
  w(`#### ${sec.title}`);
  w();
  w(`\`${sec.id}\`${sec.opt_in ? ` · opt-in: \`${sec.opt_in}\`` : ''}`);
  w();
  for (const p of sec.principles || []) w(`- ${p}`);
  if (sec.principles) w();
  for (const el of sec.elements) {
    w(`##### ${el.name}${el.opt_in ? ` (opt-in: \`${el.opt_in}\`)` : ''}`);
    w();
    if (el.properties) table(el.properties);
    if (el.fallback) { w(`Where unsupported: ${el.fallback}`); w(); }
    for (const n of el.notes || []) { w(`> ${n}`); w(); }
  }
}

w('---');
w();
w(`Generated from spec.json by tools/build-spec.mjs. Do not edit this file — edit spec.json and regenerate.`);
w();

return out.join('\n');
}

/* Importing this module must not write SPEC.md: check.mjs imports
   buildSpecMd() to regenerate and compare, and a write at import time would
   make that comparison always pass. */
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const spec = JSON.parse(readFileSync('spec.json', 'utf8'));
  const md = buildSpecMd(spec);
  writeFileSync('SPEC.md', md);
  const elements = spec.sections.reduce((n, s) => n + s.elements.length, 0);
  console.log(`SPEC.md — ${md.split('\n').length} lines, ${spec.sections.length} sections, `
    + `${elements} elements`);
}
